### ISSUE TITLE
[Task] 리팩토링

### ISSUE THREAD

**Issue by mihnhyuk** [codestates/WBABEProject-23#22]
# ISSUE
-Group : "server"
-Type: "리펙토링"

### TODO
- [ ] 응답 객체 만들기
- [ ] uri 네이밍 수정하기
- [ ] 메뉴 콜렉션 분리
- [ ] 함수 네이밍 수정하기
- [ ] 입력 벨리데이팅 하기
