### ISSUE TITLE
[Task] api 설계

### ISSUE THREAD

**Issue by mihnhyuk** [codestates/WBABEProject-23#6]
# ISSUE
-Group : "server"
-Type: "feature"

### TODO
- [x] 메뉴 등록 - 피주문자
- [x] 메뉴 수정/삭제 - 피주문자
- [x] 메뉴 리스트 출력 조회 - 주문자
- [x] 메뉴별 평점 및 리뷰 조회 - 주문자
- [x] 메뉴별 평점 작성 - 주문자
- [x] 주문 - 주문자
- [x] 주문 변경 - 주문자
- [x] 주문 내역 조회 - 주문자
- [x] 주문 상태 조회 - 피주문자
- [x] 주문 상태 변경 - 피주문자
